package com.spa.screens;/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.*;
import java.awt.*;

/**
 * @author satyanarayana.y
 */
public class Reports extends JPanel {

    /**
     * Creates new form com.spa.screens.Reports
     */
    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JLabel incomeLabel;
    private JPanel incomePanel;
    private JLabel incomeValue;
    private JLabel visitLabel;
    private JPanel visitPanel;
    private JLabel visitValue;
    public Reports() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    private void initComponents() {

        incomePanel = new JPanel();
        incomeValue = new JLabel();
        visitPanel = new JPanel();
        visitValue = new JLabel();
        incomeLabel = new JLabel();
        visitLabel = new JLabel();

        setBackground(new Color(216, 235, 243));

        incomeValue.setFont(new Font("Play", 1, 24));
        incomeValue.setText("₹ " + getIncome());

        GroupLayout incomePanelLayout = new GroupLayout(incomePanel);
        incomePanel.setLayout(incomePanelLayout);
        incomePanelLayout.setHorizontalGroup(
                incomePanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(incomePanelLayout.createSequentialGroup()
                                .addContainerGap(130, Short.MAX_VALUE)
                                .addComponent(incomeValue)
                                .addContainerGap(130, Short.MAX_VALUE))
        );
        incomePanelLayout.setVerticalGroup(
                incomePanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(incomePanelLayout.createSequentialGroup()
                                .addContainerGap(100, Short.MAX_VALUE)
                                .addComponent(incomeValue)
                                .addContainerGap(100, Short.MAX_VALUE))
        );

        visitValue.setFont(new Font("Play", 1, 24));
        visitValue.setText(Integer.toString(getVisits()));

        GroupLayout visitPanelLayout = new GroupLayout(visitPanel);
        visitPanel.setLayout(visitPanelLayout);
        visitPanelLayout.setHorizontalGroup(
                visitPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(visitPanelLayout.createSequentialGroup()
                                .addContainerGap(130, Short.MAX_VALUE)
                                .addComponent(visitValue)
                                .addContainerGap(130, Short.MAX_VALUE))
        );
        visitPanelLayout.setVerticalGroup(
                visitPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(visitPanelLayout.createSequentialGroup()
                                .addContainerGap(100, Short.MAX_VALUE)
                                .addComponent(visitValue)
                                .addContainerGap(100, Short.MAX_VALUE))
        );

        incomeLabel.setFont(new Font("Play", 1, 18));
        incomeLabel.setText("Current Month Income");

        visitLabel.setFont(new Font("Play", 1, 18));
        visitLabel.setText("Current Month Visits");

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createSequentialGroup()
                                .addContainerGap(0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addComponent(incomePanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(50,50,50)
                                                .addComponent(incomeLabel)
                                        ))
                                .addGap(130,130,130)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(50,50,50)
                                                .addComponent(visitLabel)
                                        )
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(visitPanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(0, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap(168, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addComponent(incomeLabel)
                                        .addComponent(visitLabel))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                                        .addComponent(incomePanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(visitPanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(168, Short.MAX_VALUE))
        );
    }
    // fetching total income from 1st of the month from DB which is need to be displayed in UI
    public int getIncome() {
        Database db = new Database();
        Date date = new Date();
        try {
            Date startDate = dateFormat.parse(date.getYear() + "-" + date.getMonth() + "-1");
//            ResultSet rs = db.executeQuery("select sum(s.Cost) as monthIncome from Service s, Appointment a where a.ServiceID=s.ID and a.AppointmentDate>=? and a.IsActive=true and a.AppointmentDate<?", dateFormat.format(startDate), dateFormat.format(date));
            ResultSet rs = db.executeQuery("select sum(s.Cost) as monthIncome from Service s, Appointment a where a.ServiceID=s.ID and IsPaid=true and IsDone=true");
            while (rs.next()) {
                return rs.getInt("monthIncome");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return 0;
    }
    // fetching no of visits from 1st of the month from DB which is need to be displayed in UI
    public int getVisits() {
        Database db = new Database();
        Date date = new Date();
        try {
            Date startDate = dateFormat.parse(date.getYear() + "-" + date.getMonth() + "-1");
//            ResultSet rs = db.executeQuery("select count(*) as visits from Appointment where AppointmentDate>=? and IsActive=true and AppointmentDate<?", dateFormat.format(startDate), dateFormat.format(date));
            ResultSet rs = db.executeQuery("select count(*) as visits from Appointment where IsPaid=true and IsDone=true");

            while (rs.next()) {
                return rs.getInt("visits");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return 0;
    }

}
