import java.awt.*;

public class AppointmentPanel extends javax.swing.JPanel {

/**
 * Creates new form NewJPanel12
 */
Appointment appointment;
public AppointmentPanel(Integer appointmentId,boolean isEditable) {
        appointment=getAppointmentDetails(appointmentId);
        initComponents(isEditable);
        }

        private Appointment getAppointmentDetails(Integer appointmentId) {
        return null;
        }

        /**
 * This method is called from within the constructor to initialize the form.
 * WARNING: Do NOT modify this code. The content of this method is always
 * regenerated by the Form Editor.
 */
@SuppressWarnings("unchecked")
// <editor-fold defaultstate="collapsed" desc="Generated Code">
private void initComponents(boolean isEditable) {

        backLabel = new javax.swing.JButton();
        addAppointmentLabel = new javax.swing.JLabel();
        submitLabel = new javax.swing.JButton();
        clientNameLabel = new javax.swing.JLabel();
        phoneNumberLabel = new javax.swing.JLabel();
        serviceLabel = new javax.swing.JLabel();
        therapistLabel = new javax.swing.JLabel();
        appointmentDateLabel = new javax.swing.JLabel();
        appointmentTimeLabel = new javax.swing.JLabel();
        clientNameTxt = new javax.swing.JTextField();
        phoneNumberTxt = new javax.swing.JTextField();
        serviceListSelector = new javax.swing.JComboBox<>();
        therapistListSelector = new javax.swing.JComboBox<>();
        appointmentDateTxt = new javax.swing.JFormattedTextField();
        appointmentTimeTxt = new javax.swing.JFormattedTextField();

        setBackground(new java.awt.Color(216, 235, 243));

        backLabel.setBackground(new java.awt.Color(53, 183, 234));
        backLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        backLabel.setText("BACK");
        backLabel.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                        backLabelActionPerformed(evt);
                }
        });

        addAppointmentLabel.setBackground(new java.awt.Color(216, 235, 243));
        addAppointmentLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        addAppointmentLabel.setText("ADD APPOINTMENT");

        submitLabel.setBackground(new java.awt.Color(53, 183, 234));
        submitLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        submitLabel.setText("CREATE");
        submitLabel.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                        submitLabelActionPerformed(evt);
                }
        });

        clientNameLabel.setBackground(new java.awt.Color(216, 235, 243));
        clientNameLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        clientNameLabel.setText("CLIENT NAME");

        phoneNumberLabel.setBackground(new java.awt.Color(216, 235, 243));
        phoneNumberLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        phoneNumberLabel.setText("CLIENT PHONE NUMBER");

        serviceLabel.setBackground(new java.awt.Color(216, 235, 243));
        serviceLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        serviceLabel.setText("SERVICE");

        therapistLabel.setBackground(new java.awt.Color(216, 235, 243));
        therapistLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        therapistLabel.setText("THERAPIST");

        appointmentDateLabel.setBackground(new java.awt.Color(216, 235, 243));
        appointmentDateLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        appointmentDateLabel.setText("APPOINTMENT DATE");

        appointmentTimeLabel.setBackground(new java.awt.Color(216, 235, 243));
        appointmentTimeLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        appointmentTimeLabel.setText("APPOINTMENT TIME");

        serviceListSelector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        therapistListSelector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        appointmentDateTxt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy-MM-dd"))));

        appointmentTimeTxt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        if(appointment!=null){
                appointmentTimeTxt.setText(appointment.getAppointmentTime().toString());
                appointmentDateTxt.setText(appointment.getAppointmentDate().toString());
                clientNameTxt.setText(Integer.toString(appointment.getClientId()));
                phoneNumberTxt.setText("sdaf");
                serviceListSelector.setSelectedItem("");
                therapistListSelector.setSelectedItem("");
               if(isEditable){

               }
               else{
                       appointmentDateTxt.setEnabled(false);
                       appointmentTimeTxt.setEnabled(false);
                       clientNameTxt.setEnabled(false);
                       phoneNumberTxt.setEnabled(false);
                       serviceListSelector.setEditable(false);
                       serviceListSelector.setEnabled(false);
                       therapistListSelector.setEnabled(false);
                       therapistListSelector.setEditable(false);

               }
        }
        else{

        }


        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(29, 29, 29)
                                                .addComponent(backLabel)
                                                .addGap(351, 351, 351)
                                                .addComponent(addAppointmentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 28, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(414, 414, 414)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(phoneNumberLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(serviceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(clientNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(therapistLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(appointmentDateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(appointmentTimeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(105, 105, 105)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(appointmentDateTxt)
                                                        .addComponent(appointmentTimeTxt)
                                                        .addComponent(serviceListSelector, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(therapistListSelector, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(clientNameTxt)
                                                        .addComponent(phoneNumberTxt))))
                                .addGap(435, 435, 435))
                        .addGroup(layout.createSequentialGroup()
                                .addGap(534, 534, 534)
                                .addComponent(submitLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(backLabel)
                                        .addComponent(addAppointmentLabel))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(clientNameLabel)
                                        .addComponent(clientNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(phoneNumberLabel)
                                        .addComponent(phoneNumberTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(serviceLabel)
                                        .addComponent(serviceListSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(therapistLabel)
                                        .addComponent(therapistListSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(appointmentDateLabel)
                                        .addComponent(appointmentDateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(appointmentTimeLabel)
                                        .addComponent(appointmentTimeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)
                                .addComponent(submitLabel)
                                .addContainerGap(163, Short.MAX_VALUE))
        );
}// </editor-fold>

        private void backLabelActionPerformed(java.awt.event.ActionEvent evt) {
                // TODO add your handling code here:
                Container container = getParent();
                getParent().remove(1);
                container.add(new AppointmentsPanel(), BorderLayout.CENTER, 1);
                container.validate();
                container.repaint();
        }

        private void submitLabelActionPerformed(java.awt.event.ActionEvent evt) {
                // TODO add your handling code here:
        }


        // Variables declaration - do not modify
private javax.swing.JLabel addAppointmentLabel;
private javax.swing.JLabel appointmentDateLabel;
private javax.swing.JFormattedTextField appointmentDateTxt;
private javax.swing.JLabel appointmentTimeLabel;
private javax.swing.JFormattedTextField appointmentTimeTxt;
private javax.swing.JButton backLabel;
private javax.swing.JLabel clientNameLabel;
private javax.swing.JTextField clientNameTxt;
private javax.swing.JLabel phoneNumberLabel;
private javax.swing.JTextField phoneNumberTxt;
private javax.swing.JLabel serviceLabel;
private javax.swing.JComboBox<String> serviceListSelector;
private javax.swing.JButton submitLabel;
private javax.swing.JLabel therapistLabel;
private javax.swing.JComboBox<String> therapistListSelector;
        // End of variables declaration
        }
