import javax.swing.*;
import java.awt.*;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;

public class ServicePanel extends javax.swing.JPanel {

    /**
     * Creates new form ServicePanel
     */
    Service service;
    public ServicePanel(Integer serviceId,boolean isEditable) {
        this.service=getService(serviceId);
        initComponents(service,isEditable);
    }

    private Service getService(Integer serviceId) {
        Service currentService=null;
        Database db=new Database();
        ResultSet rs=db.executeQuery("Select * from Service where ID=?",serviceId);
        ResultSet rs1=db.executeQuery("Select AppointmentDate from Appointment where ServiceID=? order by AppointmentDate desc limit 1;",serviceId);
        try{
            while (rs.next()){
                currentService=new Service();
                currentService.setActive(rs.getBoolean("IsActive"));
                currentService.setId(rs.getInt("ID"));
                currentService.setServiceName(rs.getString("ServiceName"));
                currentService.setCost(rs.getInt("Cost"));
                currentService.setDuration(rs.getInt("Duration"));
            }
            if(rs1.next()){
                currentService.setServiceLastDate(rs1.getDate("AppointmentDate"));
            }
        }
        catch (Exception e){
            e.printStackTrace();
        }
        return currentService;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents(Service service,boolean isEditable) {

        addServiceLabel = new javax.swing.JLabel();
        serviceName = new javax.swing.JLabel();
        serviceDurationLabel = new javax.swing.JLabel();
        costLabel = new javax.swing.JLabel();
        activeLable = new javax.swing.JLabel();
        lastServiceDateLabel = new javax.swing.JLabel();
        serviceNameTxt = new javax.swing.JTextField();
        serviceDurationTxt = new javax.swing.JTextField();
        costPerClientTxt = new javax.swing.JTextField();
        lastServiceDateTxt = new javax.swing.JFormattedTextField();
        isActive = new javax.swing.JCheckBox();
        submitLabel = new javax.swing.JButton();
        backLabel = new javax.swing.JButton();
        SimpleDateFormat requiredDateFormate=new java.text.SimpleDateFormat("dd/MM/yyyy");
        lastServiceDateTxt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(requiredDateFormate)));

        setBackground(new java.awt.Color(216, 235, 243));

        addServiceLabel.setText("ADD SERVICE");

        serviceName.setBackground(new java.awt.Color(216, 235, 243));
        serviceName.setText("SERVICE NAME");

        serviceDurationLabel.setBackground(new java.awt.Color(216, 235, 243));
        serviceDurationLabel.setText("SERVICE DURATION");

        costLabel.setBackground(new java.awt.Color(216, 235, 243));
        costLabel.setText("COST PER CLIENT");

        activeLable.setBackground(new java.awt.Color(216, 235, 243));
        activeLable.setText("CURRENTLY ACTIVE");

        lastServiceDateLabel.setBackground(new java.awt.Color(216, 235, 243));
        lastServiceDateLabel.setText("LAST SERVICE DATE");

        isActive.setBackground(new java.awt.Color(216, 235, 243));

        submitLabel.setBackground(new java.awt.Color(53, 183, 234));
        submitLabel.setText("CREATE");

        backLabel.setBackground(new java.awt.Color(53, 183, 234));
        backLabel.setText("BACK");
        addServiceLabel.setFont(new Font("Play", Font.BOLD, 20));
        serviceDurationLabel.setFont(new Font("Play", Font.BOLD, 15));
        serviceName.setFont(new Font("Play", Font.BOLD, 15));
        costLabel.setFont(new Font("Play", Font.BOLD, 15));
        activeLable.setFont(new Font("Play", Font.BOLD, 15));
        lastServiceDateLabel.setFont(new Font("Play", Font.BOLD, 15));

        submitLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        backLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backLabelActionPerformed(evt);
            }
        });
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        lastServiceDateTxt.setEnabled(false);

        if(service!=null){
            serviceNameTxt.setText(service.getServiceName());
            serviceDurationTxt.setText(Integer.toString(service.getDuration()));
            costPerClientTxt.setText(Integer.toString(service.getCost()));
            isActive.setSelected(service.isActive());
            if(service.getServiceLastDate()==null)
                lastServiceDateTxt.setText("");
            else{
                Date lastServiceDate=service.getServiceLastDate();
                lastServiceDateTxt.setText(requiredDateFormate.format(lastServiceDate));
            }
            if(isEditable){
                addServiceLabel.setText("UPDATE SERVICE");
                submitLabel.setText("UPDATE");
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                        .addGap(440,440,440)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                .addComponent(serviceDurationLabel)
                                                                .addComponent(serviceName)
                                                                .addComponent(costLabel)
                                                                .addComponent(activeLable)
                                                                .addComponent(lastServiceDateLabel))
                                                        .addGap(145,145,145)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                .addComponent(isActive, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(serviceDurationTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                                                                .addComponent(costPerClientTxt)
                                                                .addComponent(lastServiceDateTxt)
                                                                .addComponent(serviceNameTxt)))
                                                .addGroup(layout.createSequentialGroup()
                                                        .addGap(59, 59, 59)
                                                        .addComponent(backLabel)
                                                        .addGap(440,440,440)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addGap(20,20,20)
                                                                                .addComponent(addServiceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addGap(35,35,35)
                                                                                .addComponent(submitLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        )
                                                                )))))                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                        .addGap(15, 15, 15)
                                                        .addComponent(backLabel))
                                                .addGroup(layout.createSequentialGroup()
                                                        .addGap(35, 35, 35)
                                                        .addComponent(addServiceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(45 ,45,45)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(serviceName)
                                                .addComponent(serviceNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(20,20,20)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(serviceDurationLabel)
                                                .addComponent(serviceDurationTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(20,20,20)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(costLabel)
                                                .addComponent(costPerClientTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(20,20,20)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(activeLable)
                                                .addComponent(isActive))
                                        .addGap(20,20,20)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(lastServiceDateLabel)
                                                .addComponent(lastServiceDateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(30, 30, 30)
                                        .addComponent(submitLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))

                );
            }
            else{
                serviceNameTxt.setEnabled(false);
                serviceDurationTxt.setEnabled(false);
                isActive.setEnabled(false);
                lastServiceDateTxt.setEnabled(false);
                costPerClientTxt.setEnabled(false);
                addServiceLabel.setText("VIEW SERVICE");
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                        .addGap(440,440,440)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                .addComponent(serviceDurationLabel)
                                                                .addComponent(serviceName)
                                                                .addComponent(costLabel)
                                                                .addComponent(activeLable)
                                                                .addComponent(lastServiceDateLabel))
                                                        .addGap(145,145,145)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                .addComponent(isActive, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(serviceDurationTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                                                                .addComponent(costPerClientTxt)
                                                                .addComponent(lastServiceDateTxt)
                                                                .addComponent(serviceNameTxt)))
                                                .addGroup(layout.createSequentialGroup()
                                                        .addGap(59, 59, 59)
                                                        .addComponent(backLabel)
                                                        .addGap(440,440,440)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addGroup(layout.createSequentialGroup()
                                                                        .addGap(20,20,20)
                                                                        .addComponent(addServiceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                ))))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                        .addGap(15, 15, 15)
                                                        .addComponent(backLabel))
                                                .addGroup(layout.createSequentialGroup()
                                                        .addGap(35, 35, 35)
                                                        .addComponent(addServiceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(45 ,45,45)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(serviceName)
                                                .addComponent(serviceNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(20,20,20)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(serviceDurationLabel)
                                                .addComponent(serviceDurationTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(20,20,20)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(costLabel)
                                                .addComponent(costPerClientTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(20,20,20)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(activeLable)
                                                .addComponent(isActive))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(lastServiceDateLabel)
                                                .addComponent(lastServiceDateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                );

            }
        }
        else if(isEditable){
            layout.setHorizontalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                    .addGap(440,440,440)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addComponent(serviceDurationLabel)
                                                            .addComponent(serviceName)
                                                            .addComponent(costLabel))
                                                    .addGap(145,145,145)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                            .addComponent(serviceDurationTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                                                            .addComponent(costPerClientTxt)
                                                            .addComponent(serviceNameTxt)))
                                            .addGroup(layout.createSequentialGroup()
                                                    .addGap(59, 59, 59)
                                                    .addComponent(backLabel)
                                                    .addGap(440,440,440)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addGroup(layout.createSequentialGroup()
                                                                    .addGap(20,20,20)
                                                                    .addComponent(addServiceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                            .addGroup(layout.createSequentialGroup()
                                                                   .addGap(35,35,35)
                                                                    .addComponent(submitLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            )
                                                    ))))
            );
            layout.setVerticalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                    .addGap(15, 15, 15)
                                                    .addComponent(backLabel))
                                            .addGroup(layout.createSequentialGroup()
                                                    .addGap(35, 35, 35)
                                                    .addComponent(addServiceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(45 ,45,45)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(serviceName)
                                            .addComponent(serviceNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(20,20,20)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(serviceDurationLabel)
                                            .addComponent(serviceDurationTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(20,20,20)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(costLabel)
                                            .addComponent(costPerClientTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(30, 30, 30)
                                    .addComponent(submitLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
            );
        }


    }// </editor-fold>

    private void backLabelActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        JViewport container = (JViewport)getParent();
        container.setView(new ServicesPanel());
        container.validate();
        container.repaint();
    }

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:

        Database db=new Database();
        if(service==null){
            if(serviceNameTxt.getText()!=null && !serviceNameTxt.getText().trim().equals("") && serviceDurationTxt.getText()!=null && costPerClientTxt.getText()!=null &&  !costPerClientTxt.getText().trim().equals("") && !serviceDurationTxt.getText().trim().equals("")) {
                    db.executeUpdate("INSERT INTO Service ( ServiceName, Duration, Cost,IsActive) VALUES(?,?,?,?)", serviceNameTxt.getText(), serviceDurationTxt.getText(),costPerClientTxt.getText(), true);
                JViewport container = (JViewport)getParent();
                container.setView(new ServicesPanel());
                    container.validate();
                    container.repaint();
                    JOptionPane.showMessageDialog(this, "Service created successfully!" );
            }
            else{
                JOptionPane.showMessageDialog(this, "Required fields can not be empty. " );
            }
        }
        else{
            if(serviceNameTxt.getText()!=null && !serviceNameTxt.getText().trim().equals("") && serviceDurationTxt.getText()!=null && costPerClientTxt.getText()!=null &&  !costPerClientTxt.getText().trim().equals("") && !serviceDurationTxt.getText().trim().equals("")) {
                db.executeUpdate("update Service set ServiceName=?, Duration=?, Cost=?, IsActive=? where ID=? ;", serviceNameTxt.getText(),serviceDurationTxt.getText(),costPerClientTxt.getText(),isActive.isSelected() , service.getId());
                JViewport container = (JViewport)getParent();
                container.setView(new ServicesPanel());
                container.validate();
                container.repaint();
                JOptionPane.showMessageDialog(this, "Service details updated successfully!" );
            }
            else{
                JOptionPane.showMessageDialog(this, "Required details can not be empty.");
            }
        }

    }


    // Variables declaration - do not modify
    private javax.swing.JLabel activeLable;
    private javax.swing.JLabel addServiceLabel;
    private javax.swing.JLabel costLabel;
    private javax.swing.JTextField costPerClientTxt;
    private javax.swing.JCheckBox isActive;
    private javax.swing.JLabel lastServiceDateLabel;
    private javax.swing.JFormattedTextField lastServiceDateTxt;
    private javax.swing.JLabel serviceDurationLabel;
    private javax.swing.JTextField serviceDurationTxt;
    private javax.swing.JLabel serviceName;
    private javax.swing.JTextField serviceNameTxt;
    private javax.swing.JButton submitLabel;
    private javax.swing.JButton backLabel;

    // End of variables declaration
}
