public class ServicePanel extends javax.swing.JPanel {

    /**
     * Creates new form ServicePanel
     */
    public ServicePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        addServiceLabel = new javax.swing.JLabel();
        serviceName = new javax.swing.JLabel();
        serviceDurationLabel = new javax.swing.JLabel();
        costLabel = new javax.swing.JLabel();
        activeLable = new javax.swing.JLabel();
        lastServiceDateLabel = new javax.swing.JLabel();
        serviceNameTxt = new javax.swing.JTextField();
        serviceDurationTxt = new javax.swing.JTextField();
        costPerClientTxt = new javax.swing.JTextField();
        lastServiceDateTxt = new javax.swing.JTextField();
        isActive = new javax.swing.JCheckBox();
        submitLabel = new javax.swing.JButton();

        setBackground(new java.awt.Color(216, 235, 243));

        addServiceLabel.setText("ADD SERVICE");

        serviceName.setBackground(new java.awt.Color(216, 235, 243));
        serviceName.setText("SERVICE NAME");

        serviceDurationLabel.setBackground(new java.awt.Color(216, 235, 243));
        serviceDurationLabel.setText("SERVICE DURATION");

        costLabel.setBackground(new java.awt.Color(216, 235, 243));
        costLabel.setText("COST PER CLIENT");

        activeLable.setBackground(new java.awt.Color(216, 235, 243));
        activeLable.setText("CURRENTLY ACTIVE");

        lastServiceDateLabel.setBackground(new java.awt.Color(216, 235, 243));
        lastServiceDateLabel.setText("LAST SERVICE DATE");

        isActive.setBackground(new java.awt.Color(216, 235, 243));

        submitLabel.setBackground(new java.awt.Color(53, 183, 234));
        submitLabel.setText("SUBMIT");
        submitLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(421, 421, 421)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(serviceDurationLabel)
                                                        .addComponent(serviceName)
                                                        .addComponent(costLabel)
                                                        .addComponent(activeLable)
                                                        .addComponent(lastServiceDateLabel))
                                                .addGap(133, 133, 133)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(isActive, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(serviceDurationTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                                                        .addComponent(costPerClientTxt)
                                                        .addComponent(lastServiceDateTxt)
                                                        .addComponent(serviceNameTxt)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(563, 563, 563)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(submitLabel)
                                                        .addComponent(addServiceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap(563, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(101, 101, 101)
                                .addComponent(addServiceLabel)
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(serviceName)
                                        .addComponent(serviceNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(serviceDurationLabel)
                                        .addComponent(serviceDurationTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(costLabel)
                                        .addComponent(costPerClientTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(activeLable)
                                        .addComponent(isActive))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lastServiceDateLabel)
                                        .addComponent(lastServiceDateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                                .addComponent(submitLabel)
                                .addGap(160, 160, 160))
        );
    }// </editor-fold>
    private void submitActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:

//        Database db=new Database();
//        System.out.println(userNameTxt.getText());
//        passwordTxt.setText(HashPassword.hashPassword(passwordTxt.getText()));
//        db.executeUpdate("INSERT INTO UserLogin ( LoginName, Password, IsAdmin, IsActive) VALUES(?,?,?,?)",userNameTxt.getText(),passwordTxt.getText(),isAdmin.isSelected(),true);

    }


    // Variables declaration - do not modify
    private javax.swing.JLabel activeLable;
    private javax.swing.JLabel addServiceLabel;
    private javax.swing.JLabel costLabel;
    private javax.swing.JTextField costPerClientTxt;
    private javax.swing.JCheckBox isActive;
    private javax.swing.JLabel lastServiceDateLabel;
    private javax.swing.JTextField lastServiceDateTxt;
    private javax.swing.JLabel serviceDurationLabel;
    private javax.swing.JTextField serviceDurationTxt;
    private javax.swing.JLabel serviceName;
    private javax.swing.JTextField serviceNameTxt;
    private javax.swing.JButton submitLabel;
    // End of variables declaration
}
