import javax.swing.*;
import java.awt.*;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.List;

public class ServicesPanel extends javax.swing.JPanel {

    /**
     * Creates new form servicesPanel
     */
    public ServicesPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        addService = new javax.swing.JButton();
        serviceListScrollPane = new javax.swing.JScrollPane();
        serviceListPanel = new javax.swing.JPanel();

        setBackground(new java.awt.Color(216, 235, 243));

        addService.setBackground(new java.awt.Color(53, 183, 234));
        addService.setText("ADD");
        addService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addserviceActionPerformed(evt);
            }
        });

        serviceListPanel.setBackground(new java.awt.Color(216, 235, 243));

        javax.swing.GroupLayout serviceListPanelLayout = new javax.swing.GroupLayout(serviceListPanel);
        serviceListPanel.setLayout(serviceListPanelLayout);
        serviceListPanelLayout.setHorizontalGroup(
                serviceListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 748, Short.MAX_VALUE)
        );
        serviceListPanelLayout.setVerticalGroup(
                serviceListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 518, Short.MAX_VALUE)
        );

        serviceListScrollPane.setViewportView(serviceListPanel);
        serviceListScrollPane.setBorder(null);
        serviceListPanel.setLayout(new BoxLayout(serviceListPanel, BoxLayout.Y_AXIS));
//        FlowLayout flowLayout=new FlowLayout(FlowLayout.RIGHT,0,0);
//        flowLayout.setAlignment(FlowLayout.RIGHT);
//        serviceListPanel.setLayout(flowLayout);
        List<JPanel> services=getUserservices();
        for(int i=0;i<services.size();i++){
            serviceListPanel.add(services.get(i));
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup( layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(addService)
                                .addGap(45, 45, 45))
                        .addGroup(layout.createSequentialGroup()
                                .addGap(119, 119, 119)
                                .addComponent(serviceListScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(459, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(addService)
                                .addGap(58, 58, 58)
                                .addComponent(serviceListScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(55, Short.MAX_VALUE))
        );
    }// </editor-fold>


    private ArrayList<JPanel> getUserservices() {
        Database db=new Database();
        ArrayList<JPanel> services=new ArrayList<>();
        try {
            ResultSet rs = db.executeQuery("select * from Service");
            while (rs.next()) {
                String loginName=rs.getString("ServiceName");
//                services.add(new SingleItem());
            }
        }catch (Exception e){
            e.printStackTrace();
        }
        return services;

    }

    private void addserviceActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        Container container=getParent();
        getParent().remove(1);
        container.add(new ServicePanel(),BorderLayout.CENTER,1);
        container.validate();
        container.repaint();
    }


    // Variables declaration - do not modify
    private javax.swing.JPanel serviceListPanel;
    private javax.swing.JScrollPane serviceListScrollPane;
    private javax.swing.JButton addService;
    // End of variables declaration
}
